---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: argocd

resources:
  - managed-services