apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-load-balancer-controller
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            vertexinc.com/cluster_version: "3"
  template:
    metadata:
      name: "aws-load-balancer-controller-{{ name }}"
      labels:
        app.kubernetes.io/name: "aws-load-balancer-controller-{{ name }}"
      namespace: argocd
    spec:
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: managed-services
      destination:
        server: "{{ server }}"
        namespace: "aws-load-balancer-controller"
      source: 
        repoURL: "{{ metadata.annotations.vertexinc.com/argocd-config-repo }}"
        targetRevision: "{{ metadata.labels.vertexinc.com/revision }}"
        path: charts/umbrella-aws-load-balancer-controller
        helm:
          valueFiles:
            - values.yaml
            - values-{{ name }}.yaml
          ignoreMissingValueFiles: true
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true