reloader:
  enableHA: true
  readOnlyRootFileSystem: true
  deployment:
    replicas: 2
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    image:
      pullPolicy: Always
    livenessProbe:
      timeoutSeconds: 5
      failureThreshold: 5
      periodSeconds: 10
      successThreshold: 1
    readinessProbe:
      timeoutSeconds: 15
      failureThreshold: 5
      periodSeconds: 10
      successThreshold: 1
    resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 64Mi