apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git: 
              repoURL: https://github.com/jharlow1/argocd-jason.git 
              revision: '{{ metadata.labels.vertexinc.com/revision }}'
              files:
                - path: "clusters/{{ name }}/external-secrets/config.yaml"
  template:
    metadata:
      name: "{{ path.basename }}-{{ name }}"
      labels:
        app.kubernetes.io/name: "{{ path.basename }}-{{ name }}"
      namespace: argocd
    spec:
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: managed-services
      destination:
        server: "{{ server }}"
        namespace: "{{ path.basename }}"
      source: 
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: "{{ chartVersion }}"
        helm:
          releaseName: external-secrets
          values: |-
            replicaCount: 2
            image:
              pullPolicy: Always
            securityContext:
              capabilities:
                drop: [ALL]
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
              requests:
                cpu: 10m
                memory: 32Mi             
            webhook:
              replicaCount: 2
              image:
                pullPolicy: Always
              securityContext:
                capabilities:
                  drop: [ALL]
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
                allowPrivilegeEscalation: false
              resources:
                limits:
                  cpu: 50m
                  memory: 64Mi
                requests:
                  cpu: 10m
                  memory: 32Mi
            certController:
              image:
                pullPolicy: Always
              securityContext:
                capabilities:
                  drop: [ALL]
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
                allowPrivilegeEscalation: false
              resources:
                limits:
                  cpu: 50m
                  memory: 64Mi
                requests:
                  cpu: 10m
                  memory: 32Mi
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
