metrics-server:
  image:
    pullPolicy: Always
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    runAsUser: 1000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 70Mi
  hostNetwork:
    enabled: false