{{- if .Values.externalSecrets.enabled -}}
apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata:
  name: 'external-secrets-{{ .Values.cluster }}'
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    {{- include "commonAnnotations" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  destination:
    namespace: {{ .Values.externalSecrets.namespace }}
    server: {{ .Values.argocd.destServer }}
  ignoreDifferences:
    {{- toYaml .Values.argocd.ignoreDifferences | nindent 4 }}
    {{- if .Values.externalSecrets.ignoreDifferences }}
    {{- toYaml .Values.externalSecrets.ignoreDifferences | nindent 4 }}
    {{- end }}
  source: 
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.externalSecrets.targetRevision }}
    helm:
      releaseName: external-secrets
      values: |-
        replicaCount: {{ .Values.externalSecrets.replicas }}
        image:
          pullPolicy: Always
        securityContext:
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
        resources:
          {{- toYaml .Values.externalSecrets.resources | nindent 10 }}
        webhook:
          replicaCount: {{ .Values.externalSecrets.webhook.replicas }}
          image:
            pullPolicy: Always
          securityContext:
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.externalSecrets.webhook.resources | nindent 12 }}
        certController:
          image:
            pullPolicy: Always
          securityContext:
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.externalSecrets.webhook.resources | nindent 12 }}
        {{- with .Values.externalSecrets.values }}
        {{- . | nindent 6 }}
        {{- end }}
  syncPolicy: 
    {{- toYaml .Values.argocd.defaultSyncPolicy | nindent 4 }}
    {{- if .Values.externalSecrets.syncPolicy }}
    {{- toYaml .Values.externalSecrets.syncPolicy | nindent 4 }}
    {{- end }}
{{- end -}}

